#!/usr/bin/env node
// Regenerates README.md, index.json, and index.html (gallery) from
// explainers/*/meta.json. Directories starting with "_" are skipped.
// Usage: node scripts/build-index.mjs
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'explainers');
const REQUIRED = ['title', 'slug', 'summary', 'category', 'tags', 'format', 'date', 'status'];

const entries = [];
const problems = [];
for (const name of readdirSync(dir)) {
  if (name.startsWith('_') || name.startsWith('.')) continue;
  const metaPath = join(dir, name, 'meta.json');
  const htmlPath = join(dir, name, 'index.html');
  if (!existsSync(metaPath)) { problems.push(`${name}: missing meta.json`); continue; }
  let meta;
  try { meta = JSON.parse(readFileSync(metaPath, 'utf8')); }
  catch (e) { problems.push(`${name}: invalid JSON (${e.message})`); continue; }
  for (const f of REQUIRED) if (!(f in meta)) problems.push(`${name}: meta.json missing "${f}"`);
  if (meta.slug !== name) problems.push(`${name}: slug "${meta.slug}" != directory name`);
  if (!existsSync(htmlPath)) problems.push(`${name}: missing index.html`);
  entries.push(meta);
}
if (problems.length) {
  console.error('Index build failed:\n  ' + problems.join('\n  '));
  process.exit(1);
}
entries.sort((a, b) => b.date.localeCompare(a.date));

// --- index.json ---
writeFileSync(join(root, 'index.json'), JSON.stringify({ generated: true, count: entries.length, explainers: entries }, null, 2) + '\n');

// --- README.md ---
const byCat = {};
for (const e of entries) (byCat[e.category] ??= []).push(e);
let md = `# Process Explainers

Interactive, self-contained HTML explanatory models of complex processes.
Built with the \`matt-process-visualizer\` skill (SVG + WAAPI) and friends.

**${entries.length} explainer${entries.length === 1 ? '' : 's'}** · index auto-generated by \`scripts/build-index.mjs\` — edit \`meta.json\` files, not this table.

`;
for (const cat of Object.keys(byCat).sort()) {
  md += `## ${cat}\n\n| Explainer | Summary | Format | Date |\n|---|---|---|---|\n`;
  for (const e of byCat[cat]) {
    md += `| [${e.title}](explainers/${e.slug}/index.html) | ${e.summary} | ${e.format} | ${e.date} |\n`;
  }
  md += '\n';
}
md += `## Adding an explainer

1. Copy \`explainers/_template/\` to \`explainers/<slug>/\`
2. Drop the self-contained \`index.html\` in it and fill in \`meta.json\`
3. Run \`node scripts/build-index.mjs\`
`;
writeFileSync(join(root, 'README.md'), md);

// --- index.html gallery ---
const cards = entries.map(e => `
    <a class="card" href="explainers/${e.slug}/index.html" data-tags="${[e.category, ...e.tags].join(' ')}">
      <span class="cat">${e.category}</span>
      <h2>${e.title}</h2>
      <p>${e.summary}</p>
      <footer>${e.format} · ${e.date}${e.status !== 'published' ? ` · ${e.status}` : ''}</footer>
    </a>`).join('\n');
const tags = [...new Set(entries.flatMap(e => [e.category, ...e.tags]))].sort();
writeFileSync(join(root, 'index.html'), `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Process Explainers</title>
<style>
  :root { color-scheme: light dark; --fg: #1a1a1a; --bg: #fafafa; --card: #fff; --line: #e2e2e2; --dim: #666; }
  @media (prefers-color-scheme: dark) { :root { --fg: #e8e8e8; --bg: #131313; --card: #1d1d1d; --line: #333; --dim: #999; } }
  * { box-sizing: border-box; margin: 0; }
  body { font: 16px/1.5 system-ui, sans-serif; color: var(--fg); background: var(--bg); padding: 2rem 1rem; max-width: 64rem; margin: auto; }
  h1 { font-size: 1.6rem; margin-bottom: .25rem; }
  .sub { color: var(--dim); margin-bottom: 1.5rem; }
  .filters { display: flex; flex-wrap: wrap; gap: .4rem; margin-bottom: 1.5rem; }
  .filters button { font: inherit; font-size: .8rem; padding: .2rem .7rem; border: 1px solid var(--line); border-radius: 99px; background: var(--card); color: var(--fg); cursor: pointer; }
  .filters button.on { background: var(--fg); color: var(--bg); border-color: var(--fg); }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(16rem, 1fr)); gap: 1rem; }
  .card { display: block; padding: 1rem; background: var(--card); border: 1px solid var(--line); border-radius: .6rem; text-decoration: none; color: inherit; }
  .card:hover { border-color: var(--dim); }
  .card h2 { font-size: 1.05rem; margin: .3rem 0; }
  .card p { font-size: .88rem; color: var(--dim); }
  .card .cat { font-size: .7rem; text-transform: uppercase; letter-spacing: .06em; color: var(--dim); }
  .card footer { margin-top: .6rem; font-size: .75rem; color: var(--dim); }
  .card.hide { display: none; }
</style></head><body>
  <h1>Process Explainers</h1>
  <p class="sub">${entries.length} interactive model${entries.length === 1 ? '' : 's'} of complex processes</p>
  <div class="filters">
    <button class="on" data-tag="">all</button>
${tags.map(t => `    <button data-tag="${t}">${t}</button>`).join('\n')}
  </div>
  <div class="grid">
${cards}
  </div>
<script>
  document.querySelector('.filters').addEventListener('click', e => {
    const btn = e.target.closest('button'); if (!btn) return;
    document.querySelectorAll('.filters button').forEach(b => b.classList.toggle('on', b === btn));
    const tag = btn.dataset.tag;
    document.querySelectorAll('.card').forEach(c =>
      c.classList.toggle('hide', tag && !c.dataset.tags.split(' ').includes(tag)));
  });
</script>
</body></html>
`);
console.log(`Indexed ${entries.length} explainer(s) -> README.md, index.json, index.html`);
